# Generated by Django 3.2.8 on 2022-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.TextField(max_length=100)),
                ('stuPassword', models.TextField()),
                ('stuEmail', models.EmailField(max_length=254, unique=True)),
                ('stuPhone', models.BigIntegerField(unique=True)),
                ('admnDate', models.DateField()),
            ],
        ),
    ]
